---
site_url: https://jamesread.github.io/Faridoon/
site_name: Faridoon Docs
site_description: Documentation for Faridoon.
repo_url: https://github.com/jamesread/Faridoon
repo_name: jamesread/Faridoon
edit_uri: edit/main/docs
strict: true

markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

theme:
  name: material
  logo: faridoon.png
  favicon: faridoon.png
  language: en
  include_search_page: true
  search_index_only: true
  palette:
    primary: deep purple
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github


plugins:
  - search:
  - social:
  - minify:
      minify_html: true
  - tags:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jamesread/faridoon

    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@jamesread

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jamesreadtweets

nav:
  - Welcome: index.md
  - Installation:
      - Introduction: installation/index.md
      - Docker Compose (recommended): installation/docker-compose.md
      - Docker standalone: installation/docker.md
      - Run database migrations: installation/migrations.md
  - Configuration: configuration/index.md
  - "Security": security/index.md
  - "Contact & Support": contact-support.md
