# Sample config for /config/config.yaml
configVersion: 1
listen: ":8080"
siteTitle: Faridoon
requiredMigration: 11.cvar-category-ordinal.sql

database:
  host: mysql
  port: 3306
  name: faridoon
  user: user
  password: password

auth:
  localSessionCookieName: faridoon-sid
  baseDir: /tmp/faridoon-auth
