---
name: "Build Tag"

on:
  push:
    tags:
      - '*'

jobs:
  build-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: '8.3'

      - name: Login to ghcr
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: make container-image
        run: make docker-container-image

      - name: docker tag latest
        run: docker tag localhost/faridoon/faridoon:latest ghcr.io/jamesread/faridoon:${{ github.ref_name }}-${{ matrix.arch }}

      - name: docker push latest
        run: docker push ghcr.io/jamesread/faridoon:${{ github.ref_name }}-${{ matrix.arch }}

      - name: docker tag refname
        run: docker tag localhost/faridoon/faridoon:latest ghcr.io/jamesread/faridoon:latest

      - name: docker push refname
        run: docker push ghcr.io/jamesread/faridoon:latest


  build-docker-manifest:
    runs-on: ubuntu-latest
    needs: build-tag
    steps:

      - name: Login to ghcr
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Docker Manifest
        run: |
          docker manifest create \
            ghcr.io/jamesread/faridoon:latest \
            ghcr.io/jamesread/faridoon:${{ github.ref_name }}-amd64 \
            ghcr.io/jamesread/faridoon:${{ github.ref_name }}-arm64

          docker manifest annotate \
            ghcr.io/jamesread/faridoon:latest \
            ghcr.io/jamesread/faridoon:${{ github.ref_name }}-amd64 \
            --os linux --arch amd64

          docker manifest annotate \
            ghcr.io/jamesread/faridoon:latest \
            ghcr.io/jamesread/faridoon:${{ github.ref_name }}-arm64 \
            --os linux --arch arm64

          docker manifest push ghcr.io/jamesread/faridoon:latest
