name: "Release Pipeline"

on: [push, pull_request]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install buf
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.50.0/buf-Linux-x86_64" -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Build artifacts
        run: make generate && make -wC service build && make -wC frontend build

      - name: Login to ghcr
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        if: github.ref_type != 'tag'
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/github
          semantic_version: 24.2.3
        env:
          GH_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
