---
name: "Release Pipeline"

on: [push, pull_request]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: actions/setup-qemu@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.33.0
        with:
          php-version: '8.3'

      - name: Login to ghcr
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        if: github.ref_type != 'tag'
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/github
          semantic_version: 24.2.3  # https://github.com/cycjimmy/semantic-release-action/issues/243

        env:
          GH_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
